### ISSUE TITLE
Wildcard cert not being picked up

### ISSUE THREAD

**Issue by NicolaiVdS** [kereis/traefik-certs-dumper#117]
I have a working traefik V2 setup that maked certs for domain.tld and a sans for *.domain.tld

now when using certs dumper for domain mail.domain.tld is giving me following error
`Certificates for domain 'mail.domain.tld' don't exist. Omitting...`

this should not be the case since there is a wildcard available

**Comment by kereis** [comment]
Hi,

due to the dumping process, only the main domain of your certificates are considered for domain matching. Thus, it should be simply enough to use the main domain `domain.tld` instead of `mail.domain.tld`.

Hope that helps. :)

**Comment by NicolaiVdS** [comment]
> Hi,
> 
> due to the dumping process, only the main domain of your certificates are considered for domain matching. Thus, it should be simply enough to use the main domain `domain.tld` instead of `mail.domain.tld`.
> 
> Hope that helps. :)

this worked thx, might be usefull to add a note in the README about this ;)

**Comment by kereis** [comment]
I added a note in #119. Feel free to check if it's easy understandable and fully covers the issue. :)
