### ISSUE TITLE
Permissions issue with writing combined files

### ISSUE THREAD

**Issue by tigerkzr** [kereis/traefik-certs-dumper#118]
On a linux amd64 system

With a root:root 755 owned directory the base cert.pem and key.pem will properly be dumped . However, the subsequent combined files will not be produced in that same directory.  

I tested it with a directory under $HOME (user:user 755 owned) and the combined files were properly written.

I tried to use override pid/gid as 0:0 but it did not help with the root owned dir.  I have tried this with both latest and edge with the same results.

**Comment by kereis** [comment]
Hey, thank you for submitting this issue. I will look into it as soon as possible.

As a possible workaround: Have you already tried to `chown` in a post hook script? If you need info about this feature, please have a look at https://github.com/kereis/traefik-certs-dumper#post-hook-script.

**Comment by kereis** [comment]
This problem should be solved with #120. Please feel free to try out the `edge` builds or the later upcoming `1.6.1` release.

If there are still any issues, feel free to re-open this issue. :)
