### ISSUE TITLE
Multiarch Images

### ISSUE THREAD

**Issue by foorschtbar** [kereis/traefik-certs-dumper#138]
Any plans to support multiarch images in the future? I have experience with that and can help.

**Comment by kereis** [comment]
There are some images for other architectures. They're not under same manifest. This is because at the time of implement multi-arch support, I was afraid of not being able to switch between platforms if necessary.

I can try to take a look at it and might refer to this issue. 👍

**Comment by foorschtbar** [comment]
Thank u for the fast response. As I see, you use already the GitHub Action Workflow and the Build-Action. They are in the meantime ready for image builds with multiarch manifests. I using it since a few years now in my pipelines and can support you if you need help :)

**Comment by kereis** [comment]
Besides amd64, arm64 and arm/v7, are there any platforms that you need additionally as well?

**Comment by foorschtbar** [comment]
[multi-arch-builds-alpine](https://hub.docker.com/layers/kereis/traefik-certs-dumper/multi-arch-builds-alpine/images/sha256-e5d122886b1037a8e1ff028a2e833d4cc4c4bdc3aa75de1778b12c6de913a4cf?context=explore) works fine. Do you replace it with the latest tag?

**Comment by kereis** [comment]
Hey, sorry for the long wait. I'll release it today, but I'm currently thinking about moving it to GitHub Container Registry and/or changing tags.

**Comment by kereis** [comment]
So I tried to publish test packages via GitHub Container Registry and Docker Hub, but it looks like Docker does not like having multi-arch builds being pushed in separate docker pushes. :/

I don't know if the easiest solution is to use Docker Buildx multi-stage functionality, to merge armhf and normal Dockerfile and to try to handle different architectures in one single Dockerfile.

Do you have any suggestions @foorschtbar?

**Comment by foorschtbar** [comment]
Works fine for me one two aarch64 machines

I hope it will replace `latest` in the future :)
