### ISSUE TITLE
ACME file path

### ISSUE THREAD

**Issue by foorschtbar** [kereis/traefik-certs-dumper#139]
I tried to set a ACME_FILE_PATH via environment var in docker compose, but stdout say the cert-dumper still uses .../acme.json file. 

In the README, there is also the info that the environment var is ACME_FILE 

https://github.com/kereis/traefik-certs-dumper/blob/e57cb6627ba584687a526eae32a530e6624f340e/README.md?plain=1#L153

But they also dont work :(

**Comment by kereis** [comment]
Hey,

Sorry to hear that. On which version and arch of the images does this occur?

**Comment by foorschtbar** [comment]
Oh sorry. I use current version from the arm64v8 tag.

**Comment by foorschtbar** [comment]
With the `1-arm64v8` tags this and #137 now works fine. Will you fix the latest tag?

**Comment by kereis** [comment]
I just merged the multi arch build branch a newer image `edge` has been released which should represent the newest state of this Docker image.

Does this issue still occur? If not, please close this issue. Thanks. :)

**Comment by kereis** [comment]
Closing this issue, as there haven't been any new updates. Please feel free to re-open this issue if you need to.
