### ISSUE TITLE
no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by XenoBIT78** [kereis/traefik-certs-dumper#156]
when i try to pull  ghcr.io/kereis/traefik-certs-dumper:latest i get this error: no matching manifest for linux/amd64 in the manifest list entries

when i try to pull ghcr.io/kereis/traefik-certs-dumper:alpine i get: Error response from daemon: manifest unknown

when i try to pull ghcr.io/kereis/traefik-certs-dumper:1.6.1 i get: Error response from daemon: manifest unknown

So is it me not getting it or is it broke ?

**Comment by kereis** [comment]
Hi,

it's not really broken. There's currently no release with the new tag. The tags you can use for now is `edge`. I'm still struggling with GitHub Workflow issues where jobs for PRs by Dependabot keep receiving 403 Forbidden when logging in to GHCR. And then I sort of postponed that issue and forgot about that. 

I picked it up again. I hope I can fix it ASAP. 😅 

Sorry about that.

**Comment by XenoBIT78** [comment]
Np.. i just use the master branch which is still working fine 😊

 

Fra: Kevin Reis ***@***.***> 
Sendt: 5. august 2023 13:45
Til: kereis/traefik-certs-dumper ***@***.***>
Cc: XenoBIT78 ***@***.***>; Author ***@***.***>
Emne: Re: [kereis/traefik-certs-dumper] no matching manifest for linux/amd64 in the manifest list entries (Issue #156)

 

Hi,

it's not really broken. There's currently no release with the new tag. The tags you can use for now is edge. I'm still struggling with GitHub Workflow issues where jobs for PRs by Dependabot keep receiving 403 Forbidden when logging in to GHCR. And then I sort of postponed that issue and forgot about that.

I picked it up again. I hope I can fix it ASAP. 😅

Sorry about that.

**Comment by appiekap653** [comment]
Any updates on this issue?

Trying to use SemVer tags to have WhatsUpDocker look for updates.
With the current sha-xxxxxxx-alpine tags on the Github package, it is having trouble doing that.
If the tags where 1.6.1-alpine WUD can look for changes in Major,Minor,Patch to consider updating

**Comment by kereis** [comment]
Hey,

I'm just currently stuck on that issue where Docker crashes when manually merging manifests: https://github.com/kereis/traefik-certs-dumper/actions/runs/5770964770/job/15644469457#step:11:210

I'm well aware that I still have to create a new release, but I wanted to do that after the manifest issue is solved.

**Comment by kereis** [comment]
Good news, it might have been worth the wait 😅. I just saw that multi-arch builds for `docker` image seems to be fixed (https://github.com/docker-library/docker/issues/260#event-10505439159). That means I could remove my custom manifest merging logic as I no longer need to split up Dockerfiles anymore... hopefully. I keep you posted.

**Comment by kereis** [comment]
Hey everyone, the new multi-arch tag support was merged some time ago, however, I haven't created a new official release for this new image yet. If you want to use the new image, use tag `edge` for the latest `develop` for now. In #170, I think about how I release the new version. For now, I will close this issue. If the issue should for some reason still persist, please comment on #170 or create a new issue.
