### ISSUE TITLE
Add ENV for disable cleaning the output folder

### ISSUE THREAD

**Issue by aleritty** [kereis/traefik-certs-dumper#157]
Hi!

I'm trying to run this image to export some certificates from my traefik instance.
I want those certificates to be exported into a folder that contains also other configurations, so it will be useful to have (like with ldez's image some kind of flag that disables the cleaning of the output folder.

Also, maybe an ENV to configure the output folder would be a plus.

Thank you

**Comment by kereis** [comment]
Hi,

> I'm trying to run this image to export some certificates from my traefik instance.
> I want those certificates to be exported into a folder that contains also other configurations, so it will be useful to have (like with ldez's image some kind of flag that disables the cleaning of the output folder.

Is that a flag that can be set for ldez's traefik-certs-dumper?

> Also, maybe an ENV to configure the output folder would be a plus.
>

Is there any specific reason why you need to change the output folder inside the container? You can change the output folder on the host system via container mount.

Cheers!

**Comment by kereis** [comment]
Hi @aleritty,

it seems like this issue is stale. If my suggestion did not work out and the feature you requested is still needed, please feel free to re-open this issue. :)
