### ISSUE TITLE
Docker image tags messed up

### ISSUE THREAD

**Issue by jovobe** [kereis/traefik-certs-dumper#170]
Hi, I tried to migrate to the new image location (ghcr.io/kereis/traefik-certs-dumper) and realized, that a lot of tags are missing. E.g. all the "version" tags like :1.6.1 or :1.6 I realized as well that the :latest tag does not have a linux/amd64 variant. In my case :latest resolves to https://github.com/kereis/traefik-certs-dumper/pkgs/container/traefik-certs-dumper/90790414

**Comment by jovobe** [comment]
What's also strange is, that your last release (1.6.1) is from Dec 4, 2022 but the container got updated "6 months ago" 🤔

**Comment by erroltuparker** [comment]
I believe edge is the one that is the most up to date currently and active development.

Looking at the branches and actions, develop is the default branch which pushes to the edge release for docker.

**Comment by kereis** [comment]
Hi @jovobe,

as @erroltuparker mentioned, `edge` is the latest build of `develop` branch.

The images on Docker Hub are deprecated moving forward. The CI pipeline will push an image which simply prints the new repository URL.

Regarding newer versions from now on: I'm not sure if I should keep continuing with release 1.7, or with release 2.0 (as the new Docker tag introduces a new breaking change I guess?)

**Comment by kereis** [comment]
Hello again,

I released v1.7.0. This means, that according to GitHub, the `latest` tag refers to the latest release again (see https://github.com/kereis/traefik-certs-dumper/pkgs/container/traefik-certs-dumper).

Please try it out. :)

**Comment by kereis** [comment]
I'm closing this issue. Open a new one if you encounter any new issues!
