### ISSUE TITLE
Support non-standard acme name/location

### ISSUE THREAD

**Issue by decentral1se** [kereis/traefik-certs-dumper#40]
I have my traefik generated certs at `/etc/letsencrypt/prod-acme.json` but it seems `acme.json` is hardcoded?

https://github.com/kereis/traefik-certs-dumper/blob/d2f15d1e0b2c2efbfe83550558e2b76ecd1a1313/bin/dump.sh#L24

https://github.com/kereis/traefik-certs-dumper/blob/d2f15d1e0b2c2efbfe83550558e2b76ecd1a1313/bin/dump.sh#L347

Could we also have an env var to customise this (e.g. `ACME_PATH=/etc/letsencrypt/prod-acme.json`)?

**Comment by kereis** [comment]
Hey,

I'll put that feature into my list. Recently I also had to deal a bit with multiple `acme.json`s, so I think this will come in quite handy as well. But I don't know if we should handle only one storage file or also add the ability to handle multiple storage in one container. Taking the first option would mean that you might have to start a new container for each `acme.json`, but this approach could be more "declarative".

**Comment by decentral1se** [comment]
Thanks @kereis! I just need to have `/traefik/acme.json` replaced with a `${ACME_PATH:-/traefik/acme.json}` for the simplest case :sun_with_face:

**Comment by kereis** [comment]
Hey, check out PR #45 if it suits your needs. :) Also feel free to test.

**Comment by decentral1se** [comment]
Ah, I forgot to report in, that worked perfectly @kereis, thank you very much :heart: :100:

**Comment by deejayexe** [comment]
Hi @kereis 
I see ur new environment, but i can see to how can I adapt it to my compose:
- ACME_FILE: /my/custom/path/acme_the_second.json

This is my compose, for /share/docker/traefik/conf/acmezerossl.json i want use extractor for acmezerossl.json  is it:

version: '3.7'

services:
  certdumper:
    image: tmp/traefik-cert-dumper:latest
    container_name: extractor
    network_mode: none
    volumes:
      - /share/docker/traefik/conf/:/traefik:ro
      - /share/docker/certs/subdomain.domain.com/:/output:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    secrets:
      - pkcs12_password
    environment:
      DOMAIN: subdomain.domain.com
      PKCS12_PASSWORD_FILE: /run/secrets/pkcs12_password
      COMBINE_PKCS12: "true"
      OVERRIDE_UID: 1002
      OVERRIDE_GID: 1000

secrets:
  pkcs12_password:
    file: /share/DockerVolumes/certs/extractor_plex/PKCS12_PASSWORD

I used it with acme.json without problem but now i want for acmezerossl.json but i llite confuse with ur explanation with /my/custom/path in volumen and enviroment acme_file  but I have put the path but it gives me an error or I do not understand it according to my compose :
    volumes:
      - ./traefik/acme:/my/custom/path:ro
    
- ACME_FILE: /my/custom/path/acme_the_second.json
