### ISSUE TITLE
multiple domains problem

### ISSUE THREAD

**Issue by drag0n141** [kereis/traefik-certs-dumper#73]
hi,

i have two certificates in traefikv2. both are wildcard certificates. the problem now is the have the same ending.

*.domain.com
*.ext.domain.com

I am using the .ext.domain.com only internal this is no problem. but the certs-dumper see them as one. it extracts only the .ext.domain.com certificate. i have tested with the ENV DOMAIN and without, every combination extracts only the .ext.domain.com.

**Comment by kereis** [comment]
Hi,

could it be that there are no certificates generated for `*.domain.com` by Traefik?

**Comment by drag0n141** [comment]
The certificate is there.  I think the Problem is that both are the same domain.com names. But one with ext. in front.

**Comment by kereis** [comment]
I'm wondering if [this might be a solution](https://github.com/kereis/traefik-certs-dumper/pull/39/commits/e146fad596fcf60f4be4c8e1db05da76fd355bdc) as a part of a stale pull request.

**Comment by drag0n141** [comment]
I can Test it 😊

**Comment by drag0n141** [comment]
I have tested now the Docker from "olqs" still the Same Problem all in one.

**Comment by kereis** [comment]
Hmm.. I'm currently not sure, but maybe also check if your ACME json file uses `*.domain.com` as main `*.ext.domain.com` as SANS address? If that's the case, then the dumped certificate should be valid for both domains, shouldn't it?

**Comment by drag0n141** [comment]
No the Dumped certificate is only valid for *.ext.domain.com

**Comment by kereis** [comment]
Did you resolve your issue or does it still persist?

**Comment by drag0n141** [comment]
No still have this Problem, but now i am using ldez/traefik-certs-dumper docker with that it exports an single certificate for every domain.
