### ISSUE TITLE
fail to parse acme.json with traefik 1.7

### ISSUE THREAD

**Issue by MightyPork** [kereis/traefik-certs-dumper#74]
```
mailcowdockerized-certdumper2-1  | Error: v2: dump failed: failed to unmarshal file "/traefik/acme.json": json: cannot unmarshal array into Go value of type acme.StoredData
```

The file looks like this:

```
{
  "Account": {},
  "Certificates": [
    {
      "Domain": {
        "Main": "example.eu",
        "SANs": [
          "mail.example.eu"
        ]
      },
      "Certificate": "...==",
      "Key": "...=="
    }
  ],
  "HTTPChallenges": {},
  "TLSChallenges": {}
}
```

**Comment by kereis** [comment]
Hi,

this Docker image support Traefik v2+ only. There might be support within the underlying cert-dumper, but it's not implemented in this image. If you want, you can create a pull request and try to implement it.

**Comment by MightyPork** [comment]
It's okay, I really should just update my traefik.

I meanwhile found a different cert dumper that worked for me, after a small change: https://github.com/henkelmax/traefik-mailcow-certdumper
