### ISSUE TITLE
Merging private key and public certificate in one .pem

### ISSUE THREAD

**Issue by pkej** [kereis/traefik-certs-dumper#75]
Hi, 
The combined.pem file is created in the certs root folder and not in the domain.tld/ folder. Using only one domain that isn't added in the environment of the docker-compose file.

**Comment by kereis** [comment]
Hi,

sorry if this seems to be self-explanatory, but this means that the env var `DOMAIN` doesn't have any effect on which domains are actually dumped, but only one "random" domain is dumped?

**Comment by kereis** [comment]
Hi,

sorry that this issue went stale. I haven't kept track of it until now. This should be now fixed with #123. Please test this fix either using `edge` image or wait for the `1.6.1` release. :)
