### ISSUE TITLE
Update Hook

### ISSUE THREAD

**Issue by jwillmer** [kereis/traefik-certs-dumper#77]
I read that the `ldez/traefik-certs-dumper` supports hooks to execute some script when finishing a certificate conversion. I would like to use this in this image as well if possible. My use case is that I like to notify my admin via mail about renewed certificates that cert dumper detected/extracted.

**Comment by kereis** [comment]
Hi Jens,

I think we only need to pass the `hook.sh` to the container and adjust the args when calling `traefik-certs-dumper`.

I'll take a look into it.

**Comment by AquaWolf** [comment]
Would also love to use the update hook.sh file 👍

**Comment by kereis** [comment]
I think the hook script feature was added with v2.8.0? We have to solve #69 and #86 in beforehand before tackling this issue.

**Comment by kereis** [comment]
Issues are resolved for now.

**Comment by kereis** [comment]
> > I think we only need to pass the `hook.sh` to the container and adjust the args when calling `traefik-certs-dumper`.
> 
> 
> 
> It's probably not enough to simply pass on a file. The `--post-hook` parameter is only available in `watch` mode (see `traefic-certs-dumper --help`). But we can't use `watch` mode in this script because we rely on `inotifywait`. The solution may be that we build in our own posthook functionality... maybe this is a start: https://github.com/kereis/traefik-certs-dumper/pull/99


I realized that while implementing that feature, and I guess I can agree on that take.

**Comment by kereis** [comment]
#99 implemented a similar functionality of post-hooks like in traefik-certs-dumper -- thanks to @ggruening 😄 .
